### ISSUE TITLE
handling click/tap call 2 actions on slides

### ISSUE THREAD

**Issue by kwuite** [davidcetinkaya/hammer-slider#2]
Dear David,

I am using your slider to showcase profiles of members for certain events. Now, every user has certain clickable elements, like a message icon, or edit icon.

By utilizing the code:

`
          beforeSlideChange: (targetSlide) => {
            console.log('Changing to slide number: ' + targetSlide);
          }
`
as mentioned on github, I am able to see in the console that even clicks on my own clickable elements cause a slide change event.

How do I prevent this from happening and or better to ask, how do I make icons / buttons within the  slides clickable/tappable?

Your support in this matter is highly appreciated.

Cine Sera,

Kelvin

**Comment by davidjerleke** [comment]
Hello @kwuite,

I've published patch version 0.1.11 to address the issue with non clickable slide children. 
In order to get the latest version you can do `npm update hammer-slider` if you're using **npm** or you can just grab the minified script from this [link](https://raw.githubusercontent.com/davidcetinkaya/hammer-slider/master/dist/hammerslider.min.js).

Did that fix your issue?

Best regards,
David

**Comment by kwuite** [comment]
Dear @davidcetinkaya ,

Thank you for the swift response. I have updated the package and am no longer experiencing the event firing of "beforeSlideChange" on a simple tap or click on a slide. The slider still works very well and I see no change in quality nor performance so in my opinion the update was successful.

Unfortunately my elements are still not clickable within the slide. If I place them outside the slider container, it all works fine, but as a child element nothing happens.

I have made this video to illustrate the mechanics that I am looking for, hopefully it helps in understanding the case.

https://drive.google.com/file/d/0B5-m3MyUcpKFUHQ5YlBZc0UyeUk/view

Thank you for your support.

Cine Sera,

Kelvin

P.S.

**Just reviewed video**: I am actually clicking the message and edit icon, but the mouse is not recorded cause I am  in desktop modes trying to show you the console and html.

**Comment by kwuite** [comment]
Dear David,

Your fix actually worked out quite well, forget my last post. I went back to my original commit where I tried to increase the A element clickable size by `  a {
    float: right;
    display: inline-block;
    position: relative;
    padding: 0.6em 10.5em 0.8em 4em !important;
    margin: -0.8em -10em -0.8em -4em !important;
    z-index: 1;
  }` and that actually worked now!

Thank you very much!
